# k8s/deployment-demo.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
        labels:
          app: grafana
    spec:
      containers:
      - name: server
        image: grafana/grafana:9.5.20-ubuntu
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: 'true'
          - name: GF_INSTALL_PLUGINS
            value: redis-datasource
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: grafana-creds
                key: username
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-creds
                key: password
        volumeMounts:
          - name: grafana-datasource
            mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-datasource
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
          {
            "version": 2,
            "name": "Redis",
            "type": "redis-datasource",
            "url": "redis://redis-service:6379",
            "isDefault": true
          }
        ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000