apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-catalog
  labels:
    app: netflix-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-catalog
  template:
    metadata:
        labels:
          app: netflix-catalog
    spec:
      containers:
      - name: server
        image: davidhei/netflix:catalog-v0.0.2
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-catalog-service
spec:
  selector:
    app: netflix-catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
